apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-nfs-config # < name of the persisant volume ("pv") in kubenetes
  namespace: mediaserver # < namespace where place the pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi # < max. size we reserve for the pv
  accessModes:
    - ReadWriteMany # < Multiple pods can write to storage
  persistentVolumeReclaimPolicy: Retain # < The persistent volume can reclaimed
  nfs:
    path: /mnt/hd1/Media/plex-config # < Name of your NFS share with subfolder
    server: 192.168.18.100 # < IP number of your NFS server
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-nfs-data
  namespace: mediaserver
spec:
  storageClassName: ""
  capacity:
    storage: 300Gi # < max. size we reserve for the pv. A bigger value than the configdata
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/hd1/Media/
    server: 192.168.18.100
    readOnly: false
