kind: Service
apiVersion: v1
metadata:
  name: plex-tcp # < name of the service
  namespace: mediaserver # < namespace where to place service
  annotations:
    metallb.universe.tf/allow-shared-ip: plexserver # < annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
spec:
  selector:
    app: plexserver # < reference to the deployment (connects the service with the deployment)
  ports:
    - port: 32400 # < port to open on the outside on the server
      targetPort: 32400 # < targetport. port on the pod to passthrough
      name: pms-web # < reference name for the port in the deployment yaml
      protocol: TCP
    - port: 3005
      targetPort: 3005
      name: plex-companion
    - port: 8324
      name: plex-roku
      targetPort: 8324
      protocol: TCP
    - port: 32469
      targetPort: 32469
      name: dlna-tcp
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.18.150 # < IP to access your plexserver. Should be one from the MetalLB range and the same as the TCP yaml
---
kind: Service
apiVersion: v1
metadata:
  name: plex-tcp # < name of the service
  namespace: mediaserver # < namespace where to place service
  annotations:
    metallb.universe.tf/allow-shared-ip: plexserver # < annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
spec:
  selector:
    app: plexserver # < reference to the deployment (connects the service with the deployment)
  ports:
    - port: 32400 # < port to open on the outside on the server
      targetPort: 32400 # < targetport. port on the pod to passthrough
      name: pms-web # < reference name for the port in the deployment yaml
      protocol: TCP
    - port: 3005
      targetPort: 3005
      name: plex-companion
    - port: 8324
      name: plex-roku
      targetPort: 8324
      protocol: TCP
    - port: 32469
      targetPort: 32469
      name: dlna-tcp
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.18.150 # < IP to access your plexserver. Should be one from the MetalLB range and the same as the TCP yaml
