apiVersion: v1
kind: Namespace
metadata:
  name: deluge
  labels:
    app: deluge
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deluge-cm
  namespace: deluge
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-pv
  namespace: deluge
spec:
  storageClassName: ""
  capacity:
    storage: 512M
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/hd1/kubernetes/deluge
    server: 192.168.18.100
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: deluge
spec:
  storageClassName: ""
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/hd1/Media/
    server: 192.168.18.100
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-pvc
  namespace: deluge
spec:
  storageClassName: ""
  volumeName: deluge-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: deluge
spec:
  storageClassName: ""
  volumeName: media-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deluge
  name: deluge
  namespace: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
        - name: deluge
          image: linuxserver/deluge
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8112
          envFrom:
            - configMapRef:
                name: deluge-cm
          volumeMounts:
            - mountPath: /conf
              name: delugevol
            - mountPath: /data
              name: media-data
      volumes:
        - name: delugevol
          persistentVolumeClaim:
            claimName: deluge-pvc
        - name: media-data
          persistentVolumeClaim:
            claimName: media-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: deluge
  namespace: deluge
spec:
  selector:
    app: deluge
  ports:
    - port: 8112
      targetPort: 8112
      name: deluge-8112
      protocol: TCP
    - port: 6881
      targetPort: 6881
      name: deluge-6881
  type: LoadBalancer
  loadBalancerIP: 192.168.18.135
