apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc 
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.13.2
          ports:
            - containerPort: 3000
              name: gitea
            - containerPort: 22
              name: git-ssh
          volumeMounts:
            - mountPath: /data
              name: git-data
      volumes:
        - name: git-data
          persistentVolumeClaim:
            claimName: gitea-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  selector:
    app: gitea
  type: NodePort
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 3000
    - port: 22
      name: ssh
      targetPort: 22
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: gitea
  name: gitea-ingress
spec:
  rules:
  - host: gitea.192.168.18.150.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitea 
            port:
              number: 80
  ingressClassName: nginx
