apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hostname-deployment
spec:
  selector:
    matchLabels:
      app: hostname
  template:
    metadata:
      labels:
        app: hostname
    spec:
      containers:
      - name: hostname
        image: george124816/hostname:0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: hostname
  labels:
    app: hostname
spec:
  selector:
    app: hostname
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 4000
  loadBalancerIP: 192.168.18.130