kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-sc
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fsType: "ext4"
  nodeSelector: "storage"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: longhorn-system
  name: longhorn-ingress
spec:
  rules:
  - host: longhorn.kube.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
  ingressClassName: nginx
