kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-sc
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fsType: "ext4"
  nodeSelector: "storage"
