apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-sc
  resources:
    requests:
      storage: 300Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plexserver
  name: plexserver
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: plexserver
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plexserver
    spec:
      volumes:
        - name: plex-pvc 
          persistentVolumeClaim:
            claimName: plex-pvc
        - name: media-pvc
          persistentVolumeClaim:
            claimName: media-pvc
      nodeSelector:
        kubernetes.io/hostname: control01
      containers:
        - env:
            - name: PLEX_CLAIM
              value: "CLAIM"
            - name: PGID
              value: "\x31\x30\x30"
            - name: PUID
              value: "\x31\x30\x33\x35"
            - name: VERSION
              value: latest
            - name: TZ
              value: America/Fortaleza
          image: ghcr.io/linuxserver/plex
          imagePullPolicy: Always
          name: plexserver
          ports:
            - containerPort: 32400
              name: pms-web
              protocol: TCP
            - containerPort: 32469
              name: dlna-tcp
              protocol: TCP
            - containerPort: 1900
              name: dlna-udp
              protocol: UDP
            - containerPort: 3005
              name: plex-companion
              protocol: TCP
            - containerPort: 5353
              name: discovery-udp
              protocol: UDP
            - containerPort: 8324
              name: plex-roku
              protocol: TCP
            - containerPort: 32410
              name: gdm-32410
              protocol: UDP
            - containerPort: 32412
              name: gdm-32412
              protocol: UDP
            - containerPort: 32413
              name: gdm-32413
              protocol: UDP
            - containerPort: 32414
              name: gdm-32414
              protocol: UDP
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /config
              name: plex-pvc
            - mountPath: /data
              name: media-pvc
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: plex
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: plexserver
spec:
  selector:
    app: plexserver
  ports:
    - port: 32400
      targetPort: 32400
      name: pms-web
      protocol: TCP
    - port: 3005
      targetPort: 3005
      name: plex-companion
    - port: 8324
      name: plex-roku
      targetPort: 8324
      protocol: TCP
    - port: 32469
      targetPort: 32469
      name: dlna-tcp
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.0.0.151
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: media
  name: plex-ingress
spec:
  rules:
  - host: media.kube.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex 
            port:
              number: 32400
  ingressClassName: nginx
